Options:
  experimental features: false #Turn on experimental features
  debug: false
  proxy: false
  secret: "SECRET HERE"
  mineskin api key: "none"
  # Supported locales: en, fr, de, it, es, pt, nl, no, sv, da, fi, pl, cs, sk, hu, ro, bg, el, ru, tr, zh, ja, ko, en_US, en_GR, es_ES, es_MX, pt_BR, fr_CA
  # You must have a file with the locale you want for example messages_en_US.yml or messages_el.yml
  locale: "en_US"
  commands: #Disable or enable plugin commands
    skinoverlay: true
  updater:
    enabled: true
    download: false
    restart: false
  default skin uuid: "8667ba71-b85a-4004-af54-457a9734eed7"
  # File, MySQL, PostgreSQL, SQLite, MongoDB
  # Select in what type you want your data to be stored
  # File is recommended
  #SQL section is for MySQL(or MariaDB) and PostgreSQL
  #Default PostgreSQL port: 5432
  #Default MySQL and MariaDB port: 3306
  database:
    type: File
    SQL:
      host: localhost
      port: 3306
      user: youruser
      password: "yourpassword"
      database: SkinOverlay
      users table name: "skinoverlay_users"
      skins table name: "skinoverlay_skins"
      SQLite file name: skinoverlay
    MongoDB:
      host: "localhost"
      port: 27017
      user: youruser
      password: "yourpassword"
      database: "skinoverlay"
      collection: "skinoverlay_users"
  #Skin hooks are only used to retrieve player skin properties for offline players or players who have changed their skin.
  #Currently available Skin Hooks: None, SkinsRestorer and Custom.
  #With the custom option, you need to have your own plugin that sets the SkinOverlay.getInstance().setSkinHook(SkinHook).
  skin hook: None
  overlays:
    policeman:
      hat: true
      right_sleeve: true
      left_sleeve: true
      jacket: true
      right_pants: true
      left_pants: true
      cape: true
    mustache:
      hat: true
      right_sleeve: true
      left_sleeve: true
      jacket: true
      right_pants: true
      left_pants: true
      cape: true
    alley:
      hat: false
      right_sleeve: true
      left_sleeve: true
      jacket: true
      right_pants: true
      left_pants: true
      cape: true
    bubbo_transparent:
      hat: false
      right_sleeve: true
      left_sleeve: true
      jacket: true
      right_pants: true
      left_pants: true
      cape: true
    fire_demon:
      hat: true
      right_sleeve: true
      left_sleeve: true
      jacket: true
      right_pants: true
      left_pants: true
      cape: true
    flame:
      hat: true
      right_sleeve: true
      left_sleeve: true
      jacket: true
      right_pants: true
      left_pants: true
      cape: true
    glare:
      hat: true
      right_sleeve: true
      left_sleeve: true
      jacket: true
      right_pants: true
      left_pants: true
      cape: true
    hoodie:
      hat: true
      right_sleeve: true
      left_sleeve: true
      jacket: true
      right_pants: true
      left_pants: true
      cape: true
    migrator:
      hat: true
      right_sleeve: true
      left_sleeve: true
      jacket: true
      right_pants: true
      left_pants: true
      cape: true
    pirate:
      hat: true
      right_sleeve: true
      left_sleeve: true
      jacket: true
      right_pants: true
      left_pants: true
      cape: true
    smoking:
      hat: true
      right_sleeve: true
      left_sleeve: true
      jacket: true
      right_pants: true
      left_pants: true
      cape: true